# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: static-pages
spec:
  enabled: true
  requires: ">=2.11.0"
  author:
    name: Ryan Wang
    website: https://github.com/ruibaby
  logo: logo.svg
  homepage: https://github.com/ruibaby/plugin-static-pages#readme
  repo: https://github.com/ruibaby/plugin-static-pages
  issues: https://github.com/ruibaby/plugin-static-pages/issues
  displayName: "静态网页服务"
  description: "提供静态网页部署服务"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/ruibaby/plugin-static-pages/blob/main/LICENSE"
